version: '3.8'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: >
      sh -c "cd skillz &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn skillz.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/skillz/static
      - media_volume:/app/skillz/media  # Добавлен том для медиа файлов
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/skillz/static
      - media_volume:/app/skillz/media  # Добавлен том для медиа файлов
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:  # Добавлен том для медиа файлов
