version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app_network

  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/skillz/static
      - media_volume:/app/skillz/media
    env_file:
      - .env
    command: >
      sh -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database to be ready...'
          sleep 2
        done
        echo 'Database is ready!'
        cd skillz &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn skillz.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/skillz/static
      - media_volume:/app/skillz/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
