# Generated by Django 5.1.3 on 2024-11-10 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название курса', max_length=255, verbose_name='Название круса')),
                ('author', models.CharField(max_length=155, verbose_name='Автор курса')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('city', models.CharField(verbose_name='Адрес')),
                ('created_date', models.DateField(verbose_name='Дата создание')),
                ('updated_date', models.DateTimeField(verbose_name='Дата обновлении')),
            ],
        ),
        migrations.CreateModel(
            name='FreeWorkshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_date', models.DateField(verbose_name='Дата создание')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.FloatField(verbose_name='Цена')),
                ('created_date', models.DateField(verbose_name='Дата создание')),
                ('updated_date', models.DateTimeField(verbose_name='Дата обновлении')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_course', to='main.course', verbose_name='Курсы')),
            ],
        ),
    ]
